In [1]:
#What is Numpy

In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5])) #nd= n-dimentional

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,'niya',5+6j])

array(['1', '2', '3', '4', '5', 'niya', '(5+6j)'], dtype='<U64')

In [11]:
np.array([[1,4],[4,5]])

array([[1, 4],
       [4, 5]])

In [13]:
np.array([[2,5],[4,5],[1,5]])

array([[2, 5],
       [4, 5],
       [1, 5]])

In [14]:
np.array([[1,2,3],[2,3]])

C:\Users\Niyati Vyas\AppData\Local\Temp\ipykernel_28700\1623913609.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[2,3]])


array([list([1, 2, 3]), list([2, 3])], dtype=object)

In [15]:
np.array([[1,2],[2,1,3]])

C:\Users\Niyati Vyas\AppData\Local\Temp\ipykernel_28700\3866999890.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[2,1,3]])


array([list([1, 2]), list([2, 1, 3])], dtype=object)

In [16]:
np.array([[1,2,3],[2,4,3]])

array([[1, 2, 3],
       [2, 4, 3]])

In [19]:
np.array([1,2,3],ndmin = 3)

array([[[1, 2, 3]]])

In [20]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
np.array([1,2,3],dtype = int)

array([1, 2, 3])

In [22]:
arr=np.array([(1,2),(3,4)])

In [23]:
arr

array([[1, 2],
       [3, 4]])

In [24]:
arr[1][1]

4

In [25]:
arr[1][1]=400

In [26]:
arr

array([[  1,   2],
       [  3, 400]])

In [27]:
type(arr[1][1])

numpy.int32

# numpy==> converted into array
(np.asarray)(np.array)(np.asanyarry)

In [28]:
l=[4,1,2,3,6]

In [29]:
np.asarray(l)

array([4, 1, 2, 3, 6])

In [30]:
np.asanyarray(l)

array([4, 1, 2, 3, 6])

In [31]:
np.array(l)

array([4, 1, 2, 3, 6])

In [32]:
arr

array([[  1,   2],
       [  3, 400]])

In [33]:
b= np.copy(arr)

In [34]:
b

array([[  1,   2],
       [  3, 400]])

In [35]:
arr[0][1]=50

In [36]:
arr

array([[  1,  50],
       [  3, 400]])

In [37]:
for i in arr:
    print(i)

[ 1 50]
[  3 400]


In [38]:
np.fromfunction(lambda i,j :i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [39]:
np.fromfunction(lambda i,j :i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
np.fromfunction(lambda i,j :i/j, (3,3))

C:\Users\Niyati Vyas\AppData\Local\Temp\ipykernel_28700\795647070.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j :i/j, (3,3))
C:\Users\Niyati Vyas\AppData\Local\Temp\ipykernel_28700\795647070.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j :i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [41]:
(i*i for i in range(5))

<generator object <genexpr> at 0x000002907F82B4C0>

In [42]:
def test(x):
    yield x

In [43]:
gen= test(3)

In [44]:
np.fromiter(range(5) , dtype = int)

array([0, 1, 2, 3, 4])

In [46]:
np.fromstring('1,2,3,4' , sep =',',dtype= int)

array([1, 2, 3, 4])

In [47]:
np.fromstring('1:2' , sep =':',dtype= int)

array([1, 2])

In [48]:
np.fromstring('1:2' , sep =':',dtype= complex)

array([1.+0.j, 2.+0.j])

In [49]:
np.fromstring('1,2,3,4' , sep =',')

array([1., 2., 3., 4.])

In [50]:
l1 = [[1,2,3,4],[1,9,6,3],[1,7,3,5]]

In [51]:
arr1 = np.array(l1)

In [52]:
arr1

array([[1, 2, 3, 4],
       [1, 9, 6, 3],
       [1, 7, 3, 5]])

In [53]:
type(arr)

numpy.ndarray

In [54]:
arr1.ndim

2

In [55]:
arr1.size

12

In [56]:
arr1.shape

(3, 4)

In [58]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [59]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [60]:
np.arange(6.6,8,0.2)

array([6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ])

In [61]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [63]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
np.zeros((2,5,4)) #2= arrray(matrices),5=column,4=row

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [68]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.ones((2,3,2))+5 #5= array+5==1+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [72]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.linspace(2,4,4,endpoint =False, axis = 0 )

array([2. , 2.5, 3. , 3.5])

In [81]:
np.linspace(2,4,4, axis = 0 )

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [82]:
d=np.logspace(4,5,40)

In [83]:
d.reshape(1,2,20)

array([[[ 10000.        ,  10608.18355139,  11253.35582601,
          11937.76641714,  12663.80173467,  13433.99332599,
          14251.02670303,  15117.75070616,  16037.18743751,
          17012.54279853,  18047.21766827,  19144.8197617 ,
          20309.17620905,  21544.34690032,  22854.63864135,
          24244.62017082,  25719.13809059,  27283.33376487,
          28942.66124717,  30702.90629758],
        [ 32570.2065566 ,  34551.07294592,  36652.4123708 ,
          38881.55180308,  41246.26382901,  43754.79375074,
          46415.88833613,  49238.82631707,  52233.45074267,
          55410.20330009,  58780.16072275,  62355.07341274,
          66147.4064123 ,  70170.38286704,  74438.03013252,
          78965.228685  ,  83767.76400683,  88862.38162743,
          94266.84551179, 100000.        ]]])

In [84]:
d.reshape(2,1,20)

array([[[ 10000.        ,  10608.18355139,  11253.35582601,
          11937.76641714,  12663.80173467,  13433.99332599,
          14251.02670303,  15117.75070616,  16037.18743751,
          17012.54279853,  18047.21766827,  19144.8197617 ,
          20309.17620905,  21544.34690032,  22854.63864135,
          24244.62017082,  25719.13809059,  27283.33376487,
          28942.66124717,  30702.90629758]],

       [[ 32570.2065566 ,  34551.07294592,  36652.4123708 ,
          38881.55180308,  41246.26382901,  43754.79375074,
          46415.88833613,  49238.82631707,  52233.45074267,
          55410.20330009,  58780.16072275,  62355.07341274,
          66147.4064123 ,  70170.38286704,  74438.03013252,
          78965.228685  ,  83767.76400683,  88862.38162743,
          94266.84551179, 100000.        ]]])

In [86]:
np.random.rand(3) #its take range [0,1]

array([0.08301202, 0.96249224, 0.02274491])

In [87]:
np.random.rand(5,5)

array([[0.17576199, 0.93452683, 0.96167235, 0.53416914, 0.71670545],
       [0.47492197, 0.31503033, 0.06328861, 0.86026038, 0.12243875],
       [0.24766963, 0.73941899, 0.40234697, 0.79924611, 0.14407446],
       [0.91142643, 0.41208343, 0.68711354, 0.46269172, 0.65232258],
       [0.78710711, 0.72828988, 0.92075299, 0.84035248, 0.4819821 ]])

In [89]:
np.random.rand(3,2,5)

array([[[0.59366738, 0.65511161, 0.65695228, 0.2993657 , 0.35802626],
        [0.23603536, 0.7314884 , 0.61221967, 0.87148674, 0.53312951]],

       [[0.77948905, 0.894273  , 0.60544945, 0.32926993, 0.62817864],
        [0.33913117, 0.76985862, 0.73266359, 0.83486195, 0.12510313]],

       [[0.49716395, 0.83405881, 0.82149164, 0.63094483, 0.72994406],
        [0.11623443, 0.67972636, 0.29264873, 0.1194144 , 0.03222085]]])

In [91]:
np.random.randint(6)

5

In [92]:
np.random.randint((5,6),40)

array([ 8, 26])

In [95]:
np.random.randint(4,6,10)

array([4, 4, 5, 5, 4, 5, 4, 5, 4, 4])

In [97]:
np.random.randn(2,2)

array([[ 2.06680383,  0.16368436],
       [-1.1940959 , -0.95420655]])

In [100]:
import numpy as np
arr = np.random.randint(4,100,(5,5))

In [101]:
arr

array([[ 8, 90, 21, 79, 39],
       [37, 57,  4, 93, 40],
       [32, 74, 20, 43, 30],
       [28, 34, 85, 89,  8],
       [70, 27, 75, 44, 12]])

In [102]:
arr[2: , 2:]

array([[20, 43, 30],
       [85, 89,  8],
       [75, 44, 12]])

In [103]:
arr[0: , 2:]

array([[21, 79, 39],
       [ 4, 93, 40],
       [20, 43, 30],
       [85, 89,  8],
       [75, 44, 12]])

In [104]:
arr[1:4,1:4]

array([[57,  4, 93],
       [74, 20, 43],
       [34, 85, 89]])

In [106]:
arr[2:,:]

array([[32, 74, 20, 43, 30],
       [28, 34, 85, 89,  8],
       [70, 27, 75, 44, 12]])